In [4]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import default_rng

In [5]:
def calc_model(population):
    F_obj = np.array(population[:,0]+population[:,1]*2+population[:,2]*3+population[:,3]*4).reshape(population.shape[0],1)
    return F_obj

In [6]:
def init_genes(M):
    # Randomly init M genes
    population = np.random.randint(0,30,[M,4])
    return population
    

In [7]:
def selection(population, F_obj, crossover_rate):
    # Casino
    fitness = np.array(1/(1+F_obj)).reshape(F_obj.shape[0],1)
    total = np.sum(fitness)
    P = np.array(fitness/total).reshape(fitness.shape[0],1)
    #print('Probabilities', P)
    C = np.cumsum(P)
    C = np.insert(C, 0, 0).reshape(P.shape[0]+1,1)
    #print('Cumsum' , C.size)
    R = np.random.random(P.shape)
    #print('Random', R.size)
    sorted_population = np.zeros([population.shape[0],4])
    for i in range(R.shape[0]):
        for j in range(0, C.shape[0]):
            #print(j)
            if R[i]<C[j+1] and R[i]>=C[j]:
                sorted_population[i] = population[j]
                #print(f'Gene {j} is now at {i}' )
                break
    #print()
    R_crossover = np.random.random(P.shape)
    parents_indices = []
    #print ('Crossover chance', R_crossover)
    for i in range(sorted_population.shape[0]):
        if R_crossover[i] < crossover_rate:
            parents_indices.append(i)
    #print('Sorted ',sorted_population)
    #print('parents ', parents_indices)
    R_exchange_pos = np.random.randint(0,4,[len(parents_indices),1])
    #Crossover
    if len(parents_indices) == 0:
        pass
        #print('no parents selected')
    elif len(parents_indices) == 1:
        pass
        #print('one parent selected')
    else:
        for j in range(len(parents_indices)):
            if j==(len(parents_indices)-1):
                #print ('exchanging ',sorted_population[-1], 'with', sorted_population[0], 'at', R_exchange_pos[-1])
                sorted_population[-1][R_exchange_pos[-1]] = sorted_population[0][R_exchange_pos[-1]]
                #print('results in', sorted_population[-1])
                
            else:
                #print ('exchanging ',sorted_population[parents_indices[j]], 'with', sorted_population[parents_indices[j+1]], 'at', R_exchange_pos[j])
                sorted_population[parents_indices[j]][R_exchange_pos[j]] = sorted_population[parents_indices[j+1]][R_exchange_pos[j]]
                #print('results in', sorted_population[parents_indices[j]])
    return sorted_population

In [39]:
def mutation(population, mutation_rate):
    rng = default_rng()
    total_gen = population.size
    mutation_chance = round(mutation_rate*total_gen)
    R_mutate_indices = rng.choice(population.size, size=mutation_chance, replace=False)
    #print(R_mutate_indices)
    #R_mutate_indices = np.random.randint(0,population.size,[mutation_chance,1])
    #R_mutate_val = np.random.randint(0,30,[mutation_chance,1])
    print(population)
    print(R_mutate_indices)
    for i in R_mutate_indices:
        print(i)
        print(population[int(i/4)], int(i/4))
        population[int(i/4)][i%4] = np.random.randint(0,30,1)
        
    #print(population)
    return population

In [61]:
#np.random.seed(2)
genes = init_genes(5)
#print('Initial population \n ', genes)
for _ in range(1):
    evaluate = calc_model(genes)
    #print('Evaluate', evaluate)
    P = selection(genes, evaluate, 0.25)
    #print('Population',P)
    genes = mutation(P, 0.4)
    if 30 in evaluate:
        print('found at ', _ , genes[np.where(evaluate[:]==30)[0]])
        print('eval = ', evaluate[np.where(evaluate[:]==30)[0]])
        break


[[ 7. 23. 14.  7.]
 [17. 20. 23. 20.]
 [17. 20. 23. 20.]
 [ 7. 23. 14.  7.]
 [22. 13. 25. 27.]]
[ 0 15  4  5 11  9 13  8]
0
[ 7. 23. 14.  7.] 0
15
[ 7. 23. 14.  7.] 3
4
[17. 20. 23. 20.] 1
5
[17. 20. 23. 20.] 1
11
[17. 20. 23. 20.] 2
9
[17. 20. 23. 28.] 2
13
[ 7. 23. 14. 23.] 3
8
[17.  5. 23. 28.] 2


In [62]:
int(2/4)

0